In [2]:
# 사용할 패키지를 import합니다
import sys
print('python', sys.version)

import numpy as np
print('numpy', np.__version__)

import pandas as pd
print('pandas', pd.__version__)

import matplotlib as mpl
print('matplotlib', mpl.__version__)

import matplotlib.pyplot as plt

import seaborn as sns
print('pandas', sns.__version__)

# 결과 확인을 용이하게 하기 위한 코드
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

# # 경고 메시지는 출력되지 않게 합니다.
# import warnings
# warnings.filterwarnings("ignore")

python 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]
numpy 1.20.1
pandas 1.2.4
matplotlib 3.3.4
pandas 0.11.1

In [3]:
df1=pd.read_csv('LABEVENTS_small.csv', index_col=0)
df1

          subject_id   hadm_id  itemid  valuenum valueuom      flag
row_id
6245198        10006  142345.0   50813      4.40   mmol/L  abnormal
6245199        10006  142345.0   50861      9.00     IU/L       NaN
6245200        10006  142345.0   50862      3.40     g/dL       NaN
6245201        10006  142345.0   50863    167.00     IU/L  abnormal
6245202        10006  142345.0   50868     20.00    mEq/L       NaN
...              ...       ...     ...       ...      ...       ...
20452679       44228  103379.0   51250     88.00       fL       NaN
20452680       44228  103379.0   51265    595.00     K/uL  abnormal
20452681       44228  103379.0   51277     14.50        %       NaN
20452682       44228  103379.0   51279      2.76     m/uL  abnormal
20452683       44228  103379.0   51301     16.90     K/uL  abnormal

[61812 rows x 6 columns]

In [6]:
df1['flag']=='abnormal'

row_id
6245198      True
6245199     False
6245200     False
6245201      True
6245202     False
            ...
20452679    False
20452680     True
20452681    False
20452682     True
20452683     True
Name: flag, Length: 61812, dtype: bool

In [7]:
A=df1['itemid']==50882
B=df1((df1[A]) & (df1['flag']=='abnormal'))

MemoryError: Unable to allocate 809. MiB for an array with shape (61812, 1716) and data type float64